### ISSUE TITLE
facing GeneralError when deserializing public keys (DeserializePublicKey, DeserializePublicKeyCached)

### ISSUE THREAD

**Issue by alirezaly** [celo-org/celo-bls-go#13]
when trying to deserializeing public keys which i copied from a test case inside bls_test. there's absoluetly no context about underlyaing cause and just a general error if you could clarify in which conditions this case happens that'd be helpful.

```go
	var publicKeys []blscrypto.SerializedPublicKey
	for _, validator := range v.validators {
		publicKeys = append(publicKeys, validator.BLSPublicKey)
	}

	publicKeyObjs := []*bls.PublicKey{}
	for _, publicKey := range publicKeys {
		publicKeyObj, err := bls.DeserializePublicKeyCached(publicKey[:])
		if err != nil {
			return nil, err
		}
		defer publicKeyObj.Destroy()
		publicKeyObjs = append(publicKeyObjs, publicKeyObj)
	}
	apk, err := bls.AggregatePublicKeys(publicKeyObjs)
	if err != nil {
		return nil, err
	}
	defer apk.Destroy()
```

**Comment by kobigurk** [comment]
Can you post a compilable snippet? That will help me debug.
If not, can you share where the original public keys originated from? They are supposed to be originated from an Serialize call.

This error usually happens when the byte array is not in the right format (e.g., too many bytes).

**Comment by alirezaly** [comment]
here's the branch with the test cases
https://github.com/ChainSafe/chainbridge-celo/tree/feature/apk

**Comment by kobigurk** [comment]
Hi @alirezaly, is this still relevant?

**Comment by kobigurk** [comment]
Closing meanwhile! Feel free to re-open.
