### ISSUE TITLE
Remove per-arch go files

### ISSUE THREAD

**Issue by gakonst** [celo-org/celo-bls-go#2]
Copied from: https://github.com/celo-org/bls-zexe/issues/123

> Currently we have 1 .go file per architecture, due to the celo-blockchain toolchain being rigid for compiling with various CGO flags.
> 
> It'd be nice if we could get rid of these files, fix celo-blockchain and specify explicit instructions on how to cross-compile / link this library in various architectures.
> 
> An approach for this can be seen in https://github.com/celo-org/bls-zexe/pull/122 (which we partially reverted due to geth's inflexibility)

**Comment by kobigurk** [comment]
Still not sure it can be done. We have to tell the Go module where to look for the libraries using build tags.
